### PR TITLE
Added Linear Search in Java

### PR DESCRIPTION
**Pull request by Akriti-05**
contributing in hacktoberfest2021 
Added Linear Search algorithm in java.
Please accept or add label hacktoberfest-accepted
Thankyou!!

### CODE REVIEW

**Comment by nirala96** [comment]
@Akriti-05 please recheck as there is an empty File

**Comment by nirala96** [comment]
LGTM @Akriti-05

**Comment by Akriti-05** [comment]
Thankyou!!

**Comment by Akriti-05** [comment]
hey if possible can you please give me label of hacktober-accepted, thankyou!!

**Pull request merged**
